# Generated by Django 3.2.16 on 2023-02-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='forget_password_token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
