# Generated by Django 3.2.16 on 2023-03-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_customer_forget_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Paypal', 'Paypal'), ('Esewa', 'Esewa')], default='Cash On Delivery', max_length=20),
        ),
    ]
