# Generated by Django 3.2.16 on 2023-04-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0009_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Pending', 'Order Pending'), ('Order Received', 'Order Received'), ('Ordered Processing', 'Ordered Processing'), ('On The Way', 'On The Way'), ('Order Completed', 'Order Completed'), ('Order Canceled', 'Order Canceled')], default='Order Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Paypal', 'Paypal'), ('Paytm', 'Paytm')], default='Cash On Delivery', max_length=20),
        ),
    ]
